contact/urls.py
from django.urls import path
from contact import views

app_name='contact'
urlpatterns=[

    path ('',views.contactUs, name='contactUs'),
  

    
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='home'),
    path('search', views.search, name='search'),

]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('users.urls')),
    path('vehicles/', include('vehicle.urls')),
    path('spareParts/', include('parts.urls')),
    path('contacts/', include('contact.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.


class Contact_us(models.Model):

    sender_name=models.CharField(max_length=100)
    from_email=models.EmailField(max_length=100)
    subject=models.CharField(max_length=100)
    message=models.TextField()
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.from_email

contact/views.py
from django.shortcuts import render
from django.core.mail import send_mail,BadHeaderError
from django.contrib import messages
from contact.models import Contact_us
# Create your views here.


def contactUs(request):
    if request.method=='POST':
        sender_name= request.POST.get('sender_name')
        from_email= request.POST.get('from_email')
        subject= request.POST.get('subject')
        message= request.POST.get('message')
        admin='warriors.mart.contact@gmail.com'
        
        if subject and message and from_email:
           contact=Contact_us(sender_name=sender_name,from_email=from_email,subject=subject,message=message)
           contact.save()
           send_mail(subject,message,from_email, [admin,from_email,sender_name])
           messages.success(request,'Succesfully Send Message!')
        
         
        else:
           messages.error('Make sure all fields are entered and valid!')

    return render(request, 'contact.html')

contact/templates/contact.html
{% extends 'base.html' %}



{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contact us</title>
    <link rel="stylesheet" href="input.css">
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- for dark mode button -->
   

    <style>
        #contact_info,
        #contact_us
        {
            height: 350px;
            width: 350px;
        }
      @media only screen and (max-width:768px){
        #contact_info{display: none;} }
    </style>

</head>


<div class="h-screen w-full grid place-items-center bg-slate-100">
    {% if messages %}
    {% for msg in messages %}
    <p class="flex justify-center text-red-500 font-bold ">{{msg}}</p>
    {% endfor %}
   
    {% endif %}
    <div class="bg-white rounded-md shadow-md flex flex-row">
       

     <!-- contact information form -->
     <div id="contact_info" class="bg-blue-800 p-8 md:hover:scale-y-110 rounded-md transition md:block">
       <div class="flex justify-between">
         <!-- page title -->
         <h2 class="text-white text-xl">Contact Information</h2><br>
      
        
          <h2 class="text-white text-xs flex flex-row md:hidden block cursor-pointer" id="switch_to_contact_us">Contact Us

             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-4 w-4 ml-1">
                 <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z" clip-rule="evenodd" />
               </svg>
               
          </h2>
       </div>
       <p class="text-white flex-center text-sm">warriors mart on of the best E-commerce site </p>
       <div class="mt-6 flex flex-row">
         <div class="">
             <!-- icon -->
             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8 text-slate-200 mr-2">
                 <path fill-rule="evenodd" d="M11.54 22.351l.07.04.028.016a.76.76 0 00.723 0l.028-.015.071-.041a16.975 16.975 0 001.144-.742 19.58 19.58 0 002.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 00-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 002.682 2.282 16.975 16.975 0 001.145.742zM12 13.5a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd" />
               </svg>                  
         </div>

         <div class="">
             <h2 class="text-slate-200 text-xs">Address : </h2>
             <p class="text-white text-xs">Sylhet,Bangladesh</p>
         </div>

       </div>

       <div class="mt-6 flex flex-row">
         <div class="">
             <!-- icon -->
             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8 text-slate-200 mr-2">
                 <path fill-rule="evenodd" d="M17.834 6.166a8.25 8.25 0 100 11.668.75.75 0 011.06 1.06c-3.807 3.808-9.98 3.808-13.788 0-3.808-3.807-3.808-9.98 0-13.788 3.807-3.808 9.98-3.808 13.788 0A9.722 9.722 0 0121.75 12c0 .975-.296 1.887-.809 2.571-.514.685-1.28 1.179-2.191 1.179-.904 0-1.666-.487-2.18-1.164a5.25 5.25 0 11-.82-6.26V8.25a.75.75 0 011.5 0V12c0 .682.208 1.27.509 1.671.3.401.659.579.991.579.332 0 .69-.178.991-.579.3-.4.509-.99.509-1.671a8.222 8.222 0 00-2.416-5.834zM15.75 12a3.75 3.75 0 10-7.5 0 3.75 3.75 0 007.5 0z" clip-rule="evenodd" />
               </svg>                  
         </div>

         <div class="">
             <h2 class="text-slate-200 text-xs">Email : </h2>
             <p class="text-white text-xs">warriors.mart.contact@gmail.com</p>
         </div>
         
       </div>


       <div class="mt-6 flex flex-row">
         <div class="">
             <!-- icon -->
             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8 text-slate-200 mr-2">
                 <path fill-rule="evenodd" d="M1.5 4.5a3 3 0 013-3h1.372c.86 0 1.61.586 1.819 1.42l1.105 4.423a1.875 1.875 0 01-.694 1.955l-1.293.97c-.135.101-.164.249-.126.352a11.285 11.285 0 006.697 6.697c.103.038.25.009.352-.126l.97-1.293a1.875 1.875 0 011.955-.694l4.423 1.105c.834.209 1.42.959 1.42 1.82V19.5a3 3 0 01-3 3h-2.25C8.552 22.5 1.5 15.448 1.5 6.75V4.5z" clip-rule="evenodd" />
               </svg>                  
         </div>

         <div class="">
             <h2 class="text-slate-200 text-xs">Phone : </h2>
             <p class="text-white text-xs">+1(234)-567-890</p>
         </div>
         
       </div>

     </div>
        <!-- contact us form -->
        <div id="contact_us" class="px-6 py-8">
         <div class="flex justify-between">
             <!-- page title -->
             <h2 class="text-blue-800">Get In Touch</h2>
             <h2 class="text-red-800 text-xs flex flex-row md:hidden block cursor-pointer" id="switch_to_contact_info">Contact Us

                 <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-4 w-4 ml-1">
                     <path fill-rule="evenodd" d="M9.53 2.47a.75.75 0 010 1.06L4.81 8.25H15a6.75 6.75 0 010 13.5h-3a.75.75 0 010-1.5h3a5.25 5.25 0 100-10.5H4.81l4.72 4.72a.75.75 0 11-1.06 1.06l-6-6a.75.75 0 010-1.06l6-6a.75.75 0 011.06 0z" clip-rule="evenodd" />
                   </svg>                   
              </h2>
           </div>
         <form method="POST" action="{% url 'contact:contactUs'  %}">{% csrf_token %}
         <input type="text"  name="sender_name" placeholder="Enter Your Name" class="w-full text-xs px-3 h-8 my-2 outline-none rounded-md border focus:shadow-sm required:required"><br>
         <input type="email" placeholder="Enter Your Email" name="from_email" class="w-full text-xs px-3 h-8 my-2 outline-none rounded-md border focus:shadow-sm required:required"><br>
         <input type="text" placeholder="Subject" name="subject" class="w-full text-xs px-3 h-8 my-2 outline-none rounded-md border focus:shadow-sm"><br>
         <textarea type="text" placeholder="Enter Your Name" name="message" class="w-full text-xs py-2 px-3 h-20 my-2 outline-none rounded-md border focus:shadow-sm resize:none require:required"> </textarea><br>
         <input type="submit" value="Send" class="bg-blue-800 px-4 py-2 rounded-md text-white text-xs cursor-pointer hover:shadow-md">
         </form>
       </div>

    </div>
</div>

<script>

    let contact_info=document.querySelector('#contact_info')
    let contact_us=document.querySelector('#contact_us')
    let switch_to_contact_info=document.querySelector('#switch_to_contact_info')
    let switch_to_contact_us=document.querySelector('#switch_to_contact_us')

    switch_to_contact_us.addEventListener("click",()=>{
        contact_info.style.display='none';
        contact_us.style.display='block'
    });
    switch_to_contact_info.addEventListener("click",()=>{
        contact_info.style.display='block';
        contact_us.style.display='none';
    });
</script>



{% endblock content %}